### ISSUE TITLE
Include Vanilla Classes In Package Instead of Extending Them in the App Namespace

### ISSUE THREAD

**Issue by mikebronner** [Blogify/Blogify#10]
There are various references to the App namespace throughout the package. Instead of extending the App\Http\Controllers\Controller it might be better to include the vanilla controller in your plugin directly, thus you don't need to rely on the App namespace, or hope that the underlying project doesn't have an altered vanilla Controller class.

The Requests class is another one like this.

**Comment by jorenvh** [comment]
Thanks for the tip, will be handled.

**Comment by jorenvh** [comment]
Fixed in dev-master, will be available in the next release.
