### ISSUE TITLE
route:list command error

### ISSUE THREAD

**Issue by Hasnayeen** [Blogify/Blogify#12]
[ php artisan route:list ] gives following error
 [ErrorException]  
  Trying to get property of non-object

**Comment by Hasnayeen** [comment]
looks like the error is here jorenvanhocht\Blogify\Controllers\Admin\DashboardController.php line:71

**Comment by jorenvh** [comment]
Thanks, I take a look at it this weekend.

**Comment by bl0wfish** [comment]
Here is the fix.

https://github.com/bl0wfish/Blogify/commit/5791368829dc1a1faec76663e02d2cd2a0458404

**Comment by jorenvh** [comment]
@bl0wfish can you create a PR please.

**Comment by jorenvh** [comment]
Will be merged to master in the next release.

**Comment by jorenvh** [comment]
Available in v2.0.2
