### ISSUE TITLE
Wrong key in many-to-many relationship

### ISSUE THREAD

**Issue by Hasnayeen** [Blogify/Blogify#13]
In Tag model the key order is wrong in post method , 
        return $this->belongsToMany('jorenvanhocht\Blogify\Models\Post', 'posts_have_tags', 'post_id', 'tag_id');
which should be
        return $this->belongsToMany('jorenvanhocht\Blogify\Models\Post', 'posts_have_tags', 'tag_id', 'post_id');

**Comment by jorenvh** [comment]
Can you create a PR for it please?
