### ISSUE TITLE
vendor:publish gives "Can't locate path"

### ISSUE THREAD

**Issue by geosem42** [Blogify/Blogify#15]
Everytime I try to publish the files to the frontend I get the following errors.

> Can't locate path: </var/www/html/laravel/vendor/jorenvanhocht/blogify/src/../Views/mails/resetpassword.blade.php

I am using Laravel 5.1

```
halnex@ubuntu:/var/www/html/laravel$ sudo php artisan vendor:publish
Can't locate path: </var/www/html/laravel/vendor/jorenvanhocht/tracert/src/../config>
Copied Directory [/vendor/jorenvanhocht/blogify/config] To [/config/blogify]
Copied Directory [/vendor/jorenvanhocht/blogify/public/assets] To [/public/assets/blogify]
Copied Directory [/vendor/jorenvanhocht/blogify/public/ckeditor] To [/public/ckeditor]
Copied Directory [/vendor/jorenvanhocht/blogify/public/datetimepicker] To [/public/datetimepicker]
Can't locate path: </var/www/html/laravel/vendor/jorenvanhocht/blogify/src/../Views/admin/auth/passwordreset/>
Can't locate path: </var/www/html/laravel/vendor/jorenvanhocht/blogify/src/../Views/mails/resetpassword.blade.php>
Publishing complete for tag []!
```

Going to `http://localhost/laravel/public/admin/` works just fine, I am able to login and add new blog posts, even though it seems some javascript is not working. For example you can't add a category or tag while writing the article.

But going to `http://localhost/laravel/public/blog/` gives this error

> ReflectionException in Container.php line 736: Class App\Http\Controllers\BlogController does not exist

**Comment by jorenvh** [comment]
I fixt it in my last commit. It was a capital typo in the service provider. You should be all good again. But make sure to require the new release that I'm going to make in a few minutes.

**Comment by jorenvh** [comment]
You can pull in the new package, just run composer require jorenvanhocht/blogify 1.1-RC
