### ISSUE TITLE
Views not generated

### ISSUE THREAD

**Issue by jeanineharb** [Blogify/Blogify#16]
Hi,

When I run "php artisan blogify:generate", the views are not being generated. Any idea as to why this is happening?

Thank you.

**Comment by jorenvh** [comment]
What version of Laravel are you using? And are there any error messages?

—
Verzonden via Mailbox for Iphone

**Comment by jeanineharb** [comment]
False alarm, the views were not appearing because I did not have R&W access to the resources/views/blogify folder.

Sorry, and thank you for this great package.

**Comment by jorenvh** [comment]
No problem! And you are welcome, enjoy the package and feel free to drop me a line whit the url of your project
