### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by dhrupadshrivastava** [Blogify/Blogify#17]
![1](https://cloud.githubusercontent.com/assets/10870983/12478293/3625bace-c05a-11e5-9fb4-fa5ba7bf2038.PNG)
I am getting this error when trying to install the package please guide.
Thanks in advance

**Comment by dhrupadshrivastava** [comment]
Please inform if doing anything wrong

**Comment by jorenvh** [comment]
Hi,

Sorry this issue must haven been lost in my mailbox.

Try running:

composer require jorenvanhocht/blogify 1.1-RC

Note: make sure that the minimum stability is set to dev, for my tracert package. Blogify requires this. But both Blogify and Tracert don't have a fully stable release yet.

But everything that is there should work.

**Comment by vaghawan** [comment]
Gives the same error as reported even after setting the stability to "dev" and running composer require jorenvanhocht/blogify 1.1-RC . 
I'm not sure how should I fix it.

**Comment by jorenvh** [comment]
Running:

composer require jorenvanhocht/blogify 1.1-RC

works fine for me...
