### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by kingbri90z** [Blogify/Blogify#18]
If I run : composer require jorenvanhocht/blogify 1.0-RC

This is the result:
Problem 1
    - The requested package jorenvanhocht/blogify could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://getcomposer.org/doc/04-schema.md#minimum-stability for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

**Comment by yuri25** [comment]
If install for windows... delete directory C:\Users....you_user....\AppData\Roaming\Composer\vendor\fxp  
and again follow $  composer self-update or composer update.  It helped me.
I wonder more .... after installing dependencies missing file "config/app.php"
It is not clear which record....

> Service providers
> Now add the service provider to the providers array in "config/app.php"
> 
> 'jorenvanhocht\Blogify\BlogifyServiceProvider',

**Comment by yuri25** [comment]
Sorry ... it helped me to another problem ...
Now I have the same
Problem 1
    - The requested package jorenvanhocht/blogify could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://getcomposer.org/doc/04-schema.md#minimum-stability for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

**Comment by jorenvh** [comment]
Hi @yuri25 I just updated the entire code base over to fit Laravel 5.2. All problems should be resolved. please require v2.0.1. If you got any troubles make sure to open a new ticket.
