### ISSUE TITLE
Problems with Laravel 5.2

### ISSUE THREAD

**Issue by raphael-thibierge** [Blogify/Blogify#19]
I did : 
`$ php artisan blogify:migrate`

and i got this error : 

>   [Symfony\Component\Debug\Exception\FatalThrowableError]
>   Fatal error: Call to undefined method Illuminate\Foundation\Application::bindShared()

so i replace : 
`$this->app->bindShared('form', function($app)`
 by 
`$this->app->singleton('form', function($app)`
 in vendor/illuminate/html/HtmlServiceProvider.php line 49

then I did :
`$ php artisan blogify:migrate`

I have now this error :

>   [ErrorException]
>   Array to string conversion

I search on the web but i didn't find any solution.

If you know how to fix this, thanks !

**Comment by jorenvh** [comment]
This should be solved I just merged the code base over to Laravel 5.2
