### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by Krato** [Blogify/Blogify#2]
Hi,how to know the routes?

Or the basic functionality?

Thanks!

**Comment by jorenvh** [comment]
Hi,

You can just run php artisan route:list to get the list with the available routes for your application.

**Comment by Krato** [comment]
It looks great. But, what if you have a custom UserModel ? You need to use your UserModel. It doesn't work with custom user model :(

**Comment by jorenvh** [comment]
It does work with you custom user model. I'm sorry my docs are not completed yet but you have to make sure your custom user model uses the BlogifyUserTrait ('jorenvanhocht\Blogify\Traits\BlogifyUserTrait')

**Comment by Krato** [comment]
hehe. ok. And if you use Confident for users Roles?. Its a great package, yes. But if you need to use in an working project, its a little bit complicated. I will wait your docs.

**Comment by jorenvh** [comment]
Thanks for letting me know, so I can work on that. I will need to take a look at that part, specific for migrations etc so It does not override existing tables like the user table etc. Normally the package should be finished in the middle of June. Your feedback is appreciated and I will work on your feedback. If you find any other issues feel free to report them so I can take a look at them.

Joren

**Comment by Krato** [comment]
Thats great! I will wait your release. Thanks!
