### ISSUE TITLE
Error Installing Package

### ISSUE THREAD

**Issue by stevepop** [Blogify/Blogify#25]
I have just done a fresh Laravel installation and following your documentation, I executed `composer require jorenvanhocht/blogify v2.0`
I encountered the following error from composer,

```
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for jorenvanhocht/blogify v2.0 -> satisfiable by jorenvanhocht/blogify[v2.0].
    - jorenvanhocht/blogify v2.0 requires jorenvanhocht/tracert v1.3-RC@dev -> satisfiable by jorenvanhocht/tracert[v1.3-RC] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.
```

**Comment by jorenvh** [comment]
Hi @stevepop seems like my docs are out of date for some reason.

Please try running the command again with v2.0.3 hope that works out for you.

**Comment by stevepop** [comment]
Ok, it might be a good idea to also update your docs requirements section because while installing v2.0.3 I see that it requires Laravel 5.2.*. I will update to Laravel 5.2 and try again

**Comment by jorenvh** [comment]
Thanks, I didn't notice that the docs where out of date. I will fix this asap.

**Comment by stevepop** [comment]
Ok, I can confirm that it works with a fresh install of Laravel 5.2.
Thanks for the quick response.

**Comment by jorenvh** [comment]
Anytime, please enjoy the package and let me know if you have any trouble in the future. Or a quick testimonial of your experience.

**Comment by stevepop** [comment]
I will. Thanks!
