### ISSUE TITLE
Tracert Config Bug

### ISSUE THREAD

**Issue by stevepop** [Blogify/Blogify#26]
After running `php artisan vendor:publish` I get the error `Can't locate path: </home/steve/sandbox/laravel-blog/vendor/jorenvanhocht/tracert/src/../config>`

On looking at your TracertServiceProvider I can see in the following code where you are trying to publish the config but that path is wrong as there is no 'tracert/config' directory although I can see that you are merging the config file in 'tracert/Config/'

```
// Publish the config file
        $this->publishes([
            __DIR__.'/../config' => config_path(),
        ], 'config');
```

I hope this helps in understanding the issue.

**Comment by jorenvh** [comment]
Which version of the Tracert package is pulled in?

**Comment by stevepop** [comment]
"jorenvanhocht/tracert": "v2.0"

**Comment by jorenvh** [comment]
Ok strange, it needs version 2.0.1 that release fixed that issue. I will make a new release of blogify in a few minutes.

**Comment by jorenvh** [comment]
Blogify v2.0.4 is tagged. That should solve the issue.
