### ISSUE TITLE
Running the "blogify:generate" command fails

### ISSUE THREAD

**Issue by awjudd** [Blogify/Blogify#34]
I've been trying to run the `BlogifyGeneratePublicPartCommand` and it keeps failing trying to `mkdir`.  After going through it, it appears as though the second parameter (the `$mode`), isn't being passed in correctly.

**Comment by stevepop** [comment]
It seems the author is not merging in all the PRs so far. Any reason for this @ericvanjohnson ?

**Comment by jorenvh** [comment]
I made some time for this weekend, to handle all issues and PR and updating the docs. I am/was a little busy at work and on holiday. Sorry for that.

**Comment by awjudd** [comment]
If you need some help to manage the repository, I can assist if you would like.
