### ISSUE TITLE
demo is not working

### ISSUE THREAD

**Issue by gabak** [Blogify/Blogify#4]

**Comment by gabak** [comment]
can u pls fix the demo page cos it si not working

**Comment by jorenvh** [comment]
What is not working? Everything loads fine for so far I can see. Can you be a bit more specific?

**Comment by gabak** [comment]
working now but earlier is showing an error. thanks

**Comment by jorenvh** [comment]
Wich eeror did you get before?

**Comment by gabak** [comment]
exceptional on route something something cant really remember but it working now, thanks for ur efforts

**Comment by jorenvh** [comment]
Ok, I keep an eye out on it. Thanks for reporting.
