### ISSUE TITLE
Dependency Not Automatically Installed

### ISSUE THREAD

**Issue by mikebronner** [Blogify/Blogify#6]
I had to run `composer require jorenvanhocht/tracert 1.3-RC` manually before running `composer require jorenvanhocht/blogify 1.0-RC`, as otherwise the package installation would fail.

**Comment by jorenvh** [comment]
I just composer required Blogify myself again, but I don't seem to have any trouble?
<img width="1440" alt="schermafbeelding 2015-07-05 om 18 51 27" src="https://cloud.githubusercontent.com/assets/8791625/8512527/02da31be-2347-11e5-8997-ce728af2df6e.png">

**Comment by mikebronner** [comment]
Removed incorrect response, will respond correctly below.

**Comment by jorenvh** [comment]
mmm strange, I dig into it.

**Comment by mikebronner** [comment]
oops, sorry, mis-posted.

**Comment by mikebronner** [comment]
This is what I get on a brand new Laravel project:

``` sh
composer require jorenvanhocht/blogify 1.0-RC
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for jorenvanhocht/blogify 1.0-RC -> satisfiable by jorenvanhocht/blogify[v1.0-RC].
    - jorenvanhocht/blogify v1.0-RC requires jorenvanhocht/tracert v1.3-RC -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

**Comment by jorenvh** [comment]
Mmm strange, I can't find something wrong in my composer.json file. Hope I find the solution real quick for this weird problem.

**Comment by mikebronner** [comment]
I wonder if it might have something to do with the other package already being on your system? Is it maybe cached in composer? I will try to update my composer globally and see what happens.

**Comment by mikebronner** [comment]
While it "shouldn't" be the issue, I wonder if the 'v' in v1.3-RC is an issue? Perhaps committing the 'v'? I tried `composer require jorenvanhocht/blogify v1.0-RC` (with the 'v') and it still had the same error, so the 'v' thing is most likely not the issue.

**Comment by mikebronner** [comment]
Another thought occurred to me that it might have to do with minimum stability requirements. Perhaps the dependency would install if it was referenced with @dev at the end of the version, i.e. 1.3-RC@dev.

**Update**: that is the issue -- I changed minimum-stability in `composer.json` to dev (default is stable) and it worked. Instead of requiring composer.son to be in dev mode (which is bad for other projects, as it will pull in dev versions of packages), it is better to specify the dev flag at the dependency level. Once the decency matures, you can then simply update the decency requirement of your package to no use `@dev`.

``` json
    "require": {
        "nesbot/carbon": "~1.18",
        "guzzlehttp/guzzle": "~4.0",
        "illuminate/html": "5.0.*@dev",
        "intervention/image": "~2.1",
        "predis/predis": "~1.0",
        "jorenvanhocht/tracert": "v1.3-RC@dev"
    },
```

That should do the trick, I think.

**Comment by jorenvh** [comment]
Ok thanks, I will update the composer.json file. And indeed the minimum stability needs to be dev/release-candidate. Blogify isn't yet stable, I did not made it stable yet because of the wysiwyg problem and I knew the community would find some issues that I missed. Normally at the end of August I will make a stable release.

**Comment by jorenvh** [comment]
the dev-master branche has been updated. It will be available in the next RC/stable release. I close this issue for now.
