### ISSUE TITLE
Seed Fails If App Namespace Is Already Set

### ISSUE THREAD

**Issue by mikebronner** [Blogify/Blogify#8]
The problem is that the seed class references `App/User`. Instead you will want to get the config variable, like so:

```
    public function run()
    {
        $user = App::make(Config::get('auth.model'));
        $user->create([
            'hash'          => blogify()->makeHash('users', 'hash', true),
            'lastname'          => $this->admin['name'],
            'firstname'     => $this->admin['firstname'],
            'username'      => $this->admin['username'],
            'email'         => $this->admin['email'],
            'password'      => Hash::make($this->admin['password']),
            'role_id'       => $this->admin_role,
            'created_at'    => Carbon::now(),
            'updated_at'    => Carbon::now()
        ]);
    }
```

**Comment by jorenvh** [comment]
I put it in the next release, thanks!

**Comment by mikebronner** [comment]
I also have problems with routes if namespace doesn't equal `App`. Per the Laravel 5.1 documentation, it is not necessary to group the routes in the default namespace, so the following still works in the blogify routes file:

```
if ($use_default_routes) {
        Route::resource('blog', 'BlogController', ['only' => ['index', 'show']]);
        Route::post('blog/{slug}', [
            'as' => 'blog.confirmPass',
            'uses' => 'BlogController@show',
        ]);
        Route::get('blog/archive/{year}/{month}', [
            'as' => 'blog.archive',
            'uses' => 'BlogController@archive'
        ]);
        Route::get('blog/category/{category}', [
            'as' => 'blog.category',
            'uses' => 'BlogController@category',
        ]);
        Route::get('blog/protected/verify/{hash}', [
            'as' => 'blog.askPassword',
            'uses' => 'BlogController@askPassword'
        ]);
        Route::post('comments', [
            'as' => 'comments.store',
            'uses' => 'CommentsController@store'
        ]);
}
```

Unfortunately I haven't yet figured out how to extend from the namespaced default Controller in the Blogify BaseController. :( Look like this is going to be an issue throughout the classes that extend from the namespace classes. Perhaps the solution is to include copies of the base classes in your package, this might also ward against heavily customized base classes on already established projects.

**Comment by mikebronner** [comment]
Awesome ... as soon as I get a change I will PR these things for you, if you like. :)

**Comment by jorenvh** [comment]
You initial suggestion from this issue has been pushed to dev-master. But your second problem I don't completely understand, can you explain it in another way as above?

**Comment by mikebronner** [comment]
There are various references to the `App` namespace throughout the package. Instead of extending the `App\Http\Controllers\Controller` it might be better to include the vanilla controller in your plugin directly, thus you don't need to rely on the `App` namespace, or hope that the underlying project doesn't have an altered vanilla Controller class.

The Requests class is another one like this.

**Comment by jorenvh** [comment]
Ok I get it, I will fix this. Thanks for letting me know, didn't thought about that ;) Can you make a new issue for this so I can close this one?
