### ISSUE TITLE
Permission Denied Errors

### ISSUE THREAD

**Issue by mikebronner** [Blogify/Blogify#9]
On the commands `artisan blogify:generate --namespace="Foo"` and `artisan blogify:create-dirs` I get the following error:

```
[ErrorException]            
  mkdir(): Permission denied
```

**Comment by jorenvh** [comment]
You should check that your base folders that comes with Laravel have the right permissions. I noticed that sometimes that's not the case and you have to change the permissions manually. It's not a Blogify issue. It's weird and it's not always the case, I think it differs from the operating system you are using.

**Comment by mikebronner** [comment]
You're right, this does appear to be a systems issue involving `mkdir()`. Perhaps using                     `File::makeDirectory(public_path($path));` in `BlogifyCreateRequiredDirectories` and 

```
        if (! file_exists($path)) {
            File::makeDirectory($path);
            //            mkdir($path, 775, true);
        }
```

in `BlogifyGeneratePublicPartCommand`?

Was thinking that all filesystem commands perhaps could be executed using Laravel's internal commands. This would alleviate the responsibility of your package having to compensate for different systems to make it work (as seen with the mkdir command)? What do you think? I'd be happy to create a PR for this.

**Comment by jorenvh** [comment]
Seems like a great idea, and yes feel free to make a PR. I would do it myself but I am currently fixing my dev machine, I have some problems over there that I'm trying to fix for 3 days allready.

**Comment by mikebronner** [comment]
@jorenvh ouch! good luck with the dev machine repairs. I will work on it later this afternoon. Happy 4th of July, if you're in the USA. :)

**Comment by jorenvh** [comment]
I wish you a happy 4th of July, no I life in Belgium. And thanks hope I get it fixed soon.

**Comment by jorenvh** [comment]
replaced the mkdir function with the laravel makeDirectory function like you suggested. Committed it to dev-master, it will be available in the next release.

**Comment by mikebronner** [comment]
I have made the updates here https://github.com/GeneaLabs/Blogify/tree/feature/use-laravel-file-mechanics as well, but unfortunately haven't been able to figure out how to test them (having problems getting the fork to install via composer).
